name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t easward/react-test -f ./client/Dockerfile.dev ./client
       
      - run: docker build -t easward/multi-client-10-14 ./client
      - run: docker build -t easward/multi-nginx-10-14 ./nginx
      - run: docker build -t easward/multi-server-10-14 ./server
      - run: docker build -t easward/multi-worker-10-14 ./worker
 
      - run: docker push easward/multi-client-10-14
      - run: docker push easward/multi-nginx-10-14
      - run: docker push easward/multi-server-10-14
      - run: docker push easward/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
  
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: PokedexO2
          environment_name: Pokedex-O2-env
          existing_bucket_name: onebuckettodump
          use_existing_version_if_available: true 
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
